### ISSUE TITLE
Apt Cache very slow

### ISSUE THREAD

**Issue by skelband** [gerardpuig/ubuntu-cleaner#15]
If there are hundreds of files in the Apt Cache, then the clean up of files are extremely slow.
My suspicion is that the problem is related to the application list management itself rather the process of deleting the files.

The process speeds up as the list size is decreased until it is very rapid when there are only a few files remaining.

In my case, I have just done a system upgrade and there are more then 2000 files. The deletion starts of at a rate of 1 file per more than 2 seconds.

**Comment by gerardpuig** [comment]
Hi @skelband thanks for noticing this, I haven't tested myself with such amount of files. Could be a memory leak, feel free to investigate on this issue, if you can send a PR fixing it that would be great

**Comment by NavyBill** [comment]
This problem is still present in Ubuntu 20.10. I just upgraded and had 2154 files in the apt cache. At first, it took 2 to 3 seconds per file, then sped up to one a second around the 1100 mark. It is still plodding along at 1 per second in the 700s. What's worse, it keeps asking for Authentication so I can't simply walk away and get a cup of tea, or it will wait until I return to type my password once again.

Needs help!

Bill

**Comment by NavyBill** [comment]
More information: If I manage to click the tiny down-arrow and close the huge list of cache items, the removal immediately goes MUCH faster. I'm betting the slowness is because the list is continually being re-ordered and updated after each deletion. if you could eliminate this, you'd have a much faster removal process.

Bill

**Comment by NavyBill** [comment]
Thank you, Gerard. I am sure lots of us will be pleased. Looking forward to the update.

Bill

**Comment by gerardpuig** [comment]
Released for ubuntu 20.04, 21.10 and 22.04
