### ISSUE TITLE
Ubuntu doesn't detect new version of Ubuntu Cleaner

### ISSUE THREAD

**Issue by jqadev** [gerardpuig/ubuntu-cleaner#38]
Hi @gerardpuig,

I have installed Ubuntu Cleaner 1.0.4 on Ubuntu 18.04 and ppa is added correctly but the system doesn't detect new version 1.1.2 when I update packages

![image](https://user-images.githubusercontent.com/20422423/79758848-36cec700-831e-11ea-8c79-e450a2d171fe.png)

**Comment by gerardpuig** [comment]
Hi @jqadev that's correct, I only uploaded the latest version to ubuntu 19.10 and 20.04 ppa's. Since the version of ubuntu 18.04 was already working fine with python2 I didn't want to update it.

The main change is python3 migration so functionality wise, it's the same. Everyone is going to upgrade to LTS 20.04 soon.
