### ISSUE TITLE
Erro with python dependencies

### ISSUE THREAD

**Issue by emalherbi** [gerardpuig/ubuntu-cleaner#4]
Hi.

When I try execute this command. I get the error. Can you help-me? 

```bash
sudo apt-get update && sudo apt-get install ubuntu-cleaner
```
Error: 

```bash
Atingido:1 https://download.docker.com/linux/ubuntu xenial InRelease
Atingido:2 https://repo.skype.com/deb stable InRelease                         
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                   
Atingido:4 http://dl.google.com/linux/chrome/deb stable Release                
Atingido:6 http://ppa.launchpad.net/gerardpuig/ppa/ubuntu xenial InRelease     
Atingido:7 http://archive.ubuntu.com/ubuntu xenial InRelease                   
Atingido:8 http://ppa.launchpad.net/notepadqq-team/notepadqq/ubuntu xenial InRelease
Atingido:9 https://releases.wikimedia.org/debian jessie-mediawiki InRelease    
Atingido:10 http://ppa.launchpad.net/ondrej/apache2/ubuntu xenial InRelease    
Atingido:11 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease        
Atingido:12 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease  
Atingido:13 http://repository.spotify.com stable InRelease  
Atingido:14 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
Atingido:15 https://packages.microsoft.com/ubuntu/16.04/mssql-server xenial InRelease
Lendo listas de pacotes... Pronto
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 ubuntu-cleaner : Depende: python-lxml mas não é instalável
                  Depende: python-dbus mas não é instalável
                  Depende: python-aptdaemon mas não será instalado
                  Depende: python-aptdaemon.gtk3widgets mas não será instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.
```

```bash
sudo apt-get install python
```

```bash
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
python is already the newest version (2.7.11-1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 1 não atualizados.
```

**Comment by Bogotrax** [comment]
I am not the author of the program, but it looks as if you have dependency issues.
Maybe you try some of these options first, to go on. On these website there are different approaches, but for me mostly those help (or you have to reconfigure your sources.list first):
"One of the most basic fixes to resolve dependencies problems is to run:

sudo apt-get -f install

The -f here stands for “fix broken”. Apt will attempt to correct broken dependencies. If you manually installed a package that had unmet dependencies, apt-get will install those dependencies, if possible, otherwise it may simply remove the package that you installed in order to resolve the problem.

Then run:

sudo dpkg --configure -a

Then run this again:

sudo apt-get -f install

If the output is:

0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

That means it failed.

Next solution is to run:

sudo apt-get -u dist-upgrade

If it shows any held packages, it is best to eliminate them. Packages are held because of dependency conflicts that apt cannot resolve."

Just in case...

https://askubuntu.com/questions/140246/how-do-i-resolve-unmet-dependencies-after-adding-a-ppa

**Comment by gerardpuig** [comment]
Hi, I was just about to reply, indeed try with
`sudo apt-get -f install`

This should install the missing dependencies. What is weird though is that should come out the box with the .deb package. Which ubuntu version are you using?

**Comment by emalherbi** [comment]
Tks @Bogotrax work's for me. :+1:
