### ISSUE TITLE
elementaryOS AppCenter

### ISSUE THREAD

**Issue by jwinnie** [gerardpuig/ubuntu-cleaner#7]
It would be great if this app were uploaded to the [elementaryOS AppCenter](https://developer.elementary.io).

Steps:
- Add necessary metadata
- Test support for elementaryOS

**Comment by gerardpuig** [comment]
I prefer to stick with official Ubuntu releases, PPA is more generic for that. No time to maintain individual app centers.

Nevertheless, ubuntu cleaner should work with elementaryOS, since it's ubuntu based.

**Comment by jwinnie** [comment]
IMHO PPA requires command line knowledge, and is a security risk. I envision a future where Linux applications can be installed graphically, easily and securely.

**Comment by gerardpuig** [comment]
I do not agree that command line is less secure and is a security risk, since from the graphical interface you also have to type sudo password to install something, so same security risk as with command line.

But feel free to add support for elementaryOS and upload to their AppCenter, I'm totally fine with that.
